replicaCount: 1

image:
  repository: ghcr.io/cjtim/be-friends-api
  pullPolicy: Always
  tag: "latest"

imagePullSecrets:
  - name: ghcr.io

extraEnvs:
  - name: LINE_CLIENT_ID
    value: "1654423128"
  - name: LINE_SECRET_ID
    value: 635dfe3072be1c01549ba695b064ad3f
  - name: LINE_CALLBACK_URL
    value: https://be-friends.cjtim.com/user/line/callback
  - name: DATABASE_URL
    value: postgresql://be-friends:be-friends@psql-postgres.psql:5432/be-friends?sslmode=disable

ingress:
  enabled: true
  className: "nginx"
  annotations:
    # kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: be-friends.cjtim.com
      paths:
        - path: /api
          pathType: Prefix
  tls:
    - secretName: wildcard-cjtim-com
  #    hosts:
  #      - chart-example.local

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi