version: '3.7'

services:
  web:
    image: be-friends-fe
    ports:
      - 3000:3000
    environment:
      - BACKEND_URL=http://api:8080
  api:
    image: be-friends-api
    ports:
      - 8080:8080
    environment:
      - LINE_CLIENT_ID=
      - LINE_SECRET_ID=
      - LINE_CALLBACK_URL=http://localhost:8080/auth/line/callback
      - LOGIN_SUCCESS_URL=http://localhost:3000/user