apiVersion: v2
name: helm
description: A Helm chart for Kubernetes

type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
- name: web
  version: "v1.0.8"
  repository: "https://cjtim.github.io/be-friends"
- name: api
  version: "v1.0.14"
  repository: "https://cjtim.github.io/be-friends-api"