name: Deploy to k8s

on:
  repository_dispatch:
    types:
      - deploy-api

env:
  KUBECONFIG: kubeconfig.yaml

jobs:
  deploy:
    runs-on: ubuntu-20.04
    container:
      image: dtzar/helm-kubectl:3.9.0
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: chmod permission KUBECONFIG
        run: chmod 600 ~/.kube/config

      - name: Add helm repo
        run: helm repo add api https://cjtim.github.io/be-friends-api
      
      - name: Deploy
        run: helm upgrade api/api be-friends -f api-values.yaml -n be-friends --create-namespace
